name: Build & Publish Extension
on:
  push:
    branches: [ main ]

concurrency:
  group: build-extension-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
  id-token: write

jobs:
  build:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Bump patch version
        run: |
          newver=$(npm version patch --no-git-tag-version)
          echo "NEW_VERSION=${newver#v}" >> "$GITHUB_ENV"

      - name: Update manifest version
        run: npx dot-json src/manifest.json version "$NEW_VERSION"

      - name: Commit & tag version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json src/manifest.json
          git commit -m "chore: bump version to $NEW_VERSION"
          git tag "v$NEW_VERSION"
          git push origin HEAD --follow-tags

      - name: Build extension
        run: npm run build

      - name: Zip dist
        run: |
          cd dist
          zip -r ../extension-$NEW_VERSION.zip .

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: force-navigator-reloaded-$NEW_VERSION
          path: extension-$NEW_VERSION.zip

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.NEW_VERSION }}
          files: extension-$NEW_VERSION.zip

      - name: Publish to Chrome Web Store
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: dist/file.zip
          extension-id: ${{ secrets.CHROME_PROD_EXTENSION_ID }}
          client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          publish: false
